-- ============================================================================
-- DATA USAGE PATTERNS ANALYSIS - ARCHIVAL RECOMMENDATIONS
-- Generated: 2026-03-26 | Role: DATA_ANALYST | Account: mf90654
-- Analysis Period: Last 6 months (2025-09-26 to 2026-03-26)
-- Storage Rate: $40/TB/month (On-Demand)
-- ============================================================================

-- ============================================================================
-- STEP 8: ARCHIVAL RECOMMENDATIONS (Full Detail - 140 Tables)
-- ============================================================================
-- Run this query to regenerate the full archival recommendations report:

WITH storage AS (
    SELECT TABLE_CATALOG AS DB, TABLE_SCHEMA AS SCH, TABLE_NAME AS TBL,
           ACTIVE_BYTES, IS_TRANSIENT
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
    WHERE TABLE_CATALOG IN ('PROD_DATA','LDW','DELETED_TABLE')
      AND DELETED = FALSE AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA')
),
usage_lookback AS (
    SELECT DATABASE_NAME AS DB, SCHEMA_NAME AS SCH,
           REGEXP_SUBSTR(UPPER(QUERY_TEXT),'EBIKE_SIM_\\d+') AS TBL,
           MAX(CAST(REGEXP_SUBSTR(QUERY_TEXT,'DATEADD\\(day, -(\\d+)',1,1,'e') AS INT)) AS MAX_LOOKBACK_DAYS
    FROM SSNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE START_TIME >= DATEADD('month',-6,CURRENT_TIMESTAMP())
      AND DATABASE_NAME IN ('PROD_DATA','LDW','DELETED_TABLE')
      AND EXECUTION_STATUS = 'SUCCESS'
      AND UPPER(QUERY_TEXT) LIKE '%EBIKE_SIM_%'
      AND QUERY_TEXT LIKE '%DATEADD%'
    GROUP BY DB, SCH, TBL
),
combined AS (
    SELECT s.DB, s.SCH, s.TBL,
           s.ACTIVE_BYTES,
           ROUND(s.ACTIVE_BYTES / POWER(1024,3), 4) AS TOTAL_SIZE_GB,
           COALESCE(u.MAX_LOOKBACK_DAYS, 0) AS MAX_LOOKBACK_DAYS,
           4383 AS TOTAL_DATA_DAYS,
           CASE WHEN u.MAX_LOOKBACK_DAYS IS NULL THEN 4383
                ELSE 4383 - u.MAX_LOOKBACK_DAYS END AS ARCHIVABLE_DAYS
    FROM storage s
    LEFT JOIN usage_lookback u ON s.DB = u.DB AND s.SCH = u.SCH AND s.TBL = u.TBL
)
SELECT 
    DB AS DATABASE_NAME,
    SCH AS SCHEMA_NAME,
    TBL AS TABLE_NAME,
    ROUND(TOTAL_SIZE_GB, 2) AS "a. Total Size (GB)",
    ROUND((TOTAL_SIZE_GB / 1024) * 40, 2) AS "b. Monthly Storage Cost ($)",
    CASE WHEN MAX_LOOKBACK_DAYS = 0 
         THEN '2014-03-27 to 2026-03-24 (entire table - not queried)'
         ELSE '2014-03-27 to ' || TO_CHAR(DATEADD('day', -MAX_LOOKBACK_DAYS, '2026-03-26'::DATE), 'YYYY-MM-DD')
    END AS "c. Archivable Years (from - to)",
    ROUND(TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS), 2) AS "d. Archivable Size (GB)",
    ROUND((ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS) * 100, 2) AS "e. Archivable %",
    ROUND(((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40, 2) AS "f. Monthly Savings ($)",
    ROUND(((ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS) * 100), 2) AS "g. Monthly Savings (%)",
    ROUND(((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40 * 12, 2) AS "h. Yearly Savings ($)",
    ROUND(((ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS) * 100), 2) AS "i. Yearly Savings (%)",
    CASE WHEN MAX_LOOKBACK_DAYS = 0 THEN 'ARCHIVE'
         WHEN MAX_LOOKBACK_DAYS <= 300 THEN 'ARCHIVE'
         WHEN MAX_LOOKBACK_DAYS <= 730 THEN 'ARCHIVE'
         ELSE 'REVIEW' END AS RECOMMENDATION
FROM combined
ORDER BY DB, SCH, TBL;


-- ============================================================================
-- STEP 9: TRANSIENT TABLE CANDIDATES
-- ============================================================================
-- Tables with STG naming pattern are candidates for transient conversion.
-- Transient tables: 0-1 day Time Travel, NO Fail-safe (saves ~7 days fail-safe storage).
-- Note: All tables currently have IS_TRANSIENT = NO and FAILSAFE_BYTES = 0.

-- PROD_DATA.STG schema tables (20 tables) are candidates based on naming convention:
--   EBIKE_SIM_1 through EBIKE_SIM_20 in PROD_DATA.STG
--
-- Conversion SQL (example):
--   CREATE OR REPLACE TRANSIENT TABLE PROD_DATA.STG.EBIKE_SIM_1 AS SELECT * FROM PROD_DATA.STG.EBIKE_SIM_1;

SELECT 
    s.TABLE_CATALOG AS DATABASE_NAME,
    s.TABLE_SCHEMA AS SCHEMA_NAME,
    s.TABLE_NAME,
    s.IS_TRANSIENT AS CURRENT_IS_TRANSIENT,
    s.FAILSAFE_BYTES,
    CASE 
        WHEN s.TABLE_SCHEMA IN ('STG') THEN 'Staging/ETL naming pattern'
        ELSE 'No criteria met'
    END AS TRANSIENT_CRITERIA
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS s
WHERE s.TABLE_CATALOG IN ('PROD_DATA','LDW','DELETED_TABLE')
  AND s.DELETED = FALSE
  AND s.TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA')
ORDER BY s.TABLE_CATALOG, s.TABLE_SCHEMA, s.TABLE_NAME;


-- ============================================================================
-- STEP 10: AGGREGATED COST SAVINGS
-- ============================================================================

-- AGGREGATION 1: Per Schema
WITH storage AS (
    SELECT TABLE_CATALOG AS DB, TABLE_SCHEMA AS SCH, TABLE_NAME AS TBL,
           ACTIVE_BYTES
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
    WHERE TABLE_CATALOG IN ('PROD_DATA','LDW','DELETED_TABLE')
      AND DELETED = FALSE AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA')
),
usage_lookback AS (
    SELECT DATABASE_NAME AS DB, SCHEMA_NAME AS SCH,
           REGEXP_SUBSTR(UPPER(QUERY_TEXT),'EBIKE_SIM_\\d+') AS TBL,
           MAX(CAST(REGEXP_SUBSTR(QUERY_TEXT,'DATEADD\\(day, -(\\d+)',1,1,'e') AS INT)) AS MAX_LOOKBACK_DAYS
    FROM SSNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE START_TIME >= DATEADD('month',-6,CURRENT_TIMESTAMP())
      AND DATABASE_NAME IN ('PROD_DATA','LDW','DELETED_TABLE')
      AND EXECUTION_STATUS = 'SUCCESS'
      AND UPPER(QUERY_TEXT) LIKE '%EBIKE_SIM_%'
      AND QUERY_TEXT LIKE '%DATEADD%'
    GROUP BY DB, SCH, TBL
),
combined AS (
    SELECT s.DB, s.SCH, s.TBL,
           ROUND(s.ACTIVE_BYTES / POWER(1024,3), 4) AS TOTAL_SIZE_GB,
           4383 AS TOTAL_DATA_DAYS,
           CASE WHEN u.MAX_LOOKBACK_DAYS IS NULL THEN 4383
                ELSE 4383 - u.MAX_LOOKBACK_DAYS END AS ARCHIVABLE_DAYS
    FROM storage s
    LEFT JOIN usage_lookback u ON s.DB = u.DB AND s.SCH = u.SCH AND s.TBL = u.TBL
)
SELECT 
    DB AS DATABASE_NAME,
    SCH AS SCHEMA_NAME,
    ROUND(SUM(TOTAL_SIZE_GB), 2) AS "a. Total Size (GB)",
    ROUND(SUM(TOTAL_SIZE_GB / 1024) * 40, 2) AS "b. Monthly Cost ($)",
    ROUND(SUM(TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)), 2) AS "d. Archivable Size (GB)",
    ROUND(SUM(TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / NULLIF(SUM(TOTAL_SIZE_GB), 0) * 100, 2) AS "e. Archivable %",
    ROUND(SUM((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40, 2) AS "f. Monthly Savings ($)",
    ROUND(SUM((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40 / NULLIF(SUM(TOTAL_SIZE_GB / 1024) * 40, 0) * 100, 2) AS "g. Monthly Savings (%)",
    ROUND(SUM((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40 * 12, 2) AS "h. Yearly Savings ($)",
    ROUND(SUM((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40 * 12 / NULLIF(SUM(TOTAL_SIZE_GB / 1024) * 40 * 12, 0) * 100, 2) AS "i. Yearly Savings (%)"
FROM combined
GROUP BY DB, SCH
ORDER BY DB, SCH;


-- AGGREGATION 2: Per Database
WITH storage AS (
    SELECT TABLE_CATALOG AS DB, TABLE_SCHEMA AS SCH, TABLE_NAME AS TBL,
           ACTIVE_BYTES
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
    WHERE TABLE_CATALOG IN ('PROD_DATA','LDW','DELETED_TABLE')
      AND DELETED = FALSE AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA')
),
usage_lookback AS (
    SELECT DATABASE_NAME AS DB, SCHEMA_NAME AS SCH,
           REGEXP_SUBSTR(UPPER(QUERY_TEXT),'EBIKE_SIM_\\d+') AS TBL,
           MAX(CAST(REGEXP_SUBSTR(QUERY_TEXT,'DATEADD\\(day, -(\\d+)',1,1,'e') AS INT)) AS MAX_LOOKBACK_DAYS
    FROM SSNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE START_TIME >= DATEADD('month',-6,CURRENT_TIMESTAMP())
      AND DATABASE_NAME IN ('PROD_DATA','LDW','DELETED_TABLE')
      AND EXECUTION_STATUS = 'SUCCESS'
      AND UPPER(QUERY_TEXT) LIKE '%EBIKE_SIM_%'
      AND QUERY_TEXT LIKE '%DATEADD%'
    GROUP BY DB, SCH, TBL
),
combined AS (
    SELECT s.DB, s.SCH, s.TBL,
           ROUND(s.ACTIVE_BYTES / POWER(1024,3), 4) AS TOTAL_SIZE_GB,
           4383 AS TOTAL_DATA_DAYS,
           CASE WHEN u.MAX_LOOKBACK_DAYS IS NULL THEN 4383
                ELSE 4383 - u.MAX_LOOKBACK_DAYS END AS ARCHIVABLE_DAYS
    FROM storage s
    LEFT JOIN usage_lookback u ON s.DB = u.DB AND s.SCH = u.SCH AND s.TBL = u.TBL
)
SELECT 
    DB AS DATABASE_NAME,
    ROUND(SUM(TOTAL_SIZE_GB), 2) AS "a. Total Size (GB)",
    ROUND(SUM(TOTAL_SIZE_GB / 1024) * 40, 2) AS "b. Monthly Cost ($)",
    ROUND(SUM(TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)), 2) AS "d. Archivable Size (GB)",
    ROUND(SUM(TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / NULLIF(SUM(TOTAL_SIZE_GB), 0) * 100, 2) AS "e. Archivable %",
    ROUND(SUM((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40, 2) AS "f. Monthly Savings ($)",
    ROUND(SUM((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40 / NULLIF(SUM(TOTAL_SIZE_GB / 1024) * 40, 0) * 100, 2) AS "g. Monthly Savings (%)",
    ROUND(SUM((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40 * 12, 2) AS "h. Yearly Savings ($)",
    ROUND(SUM((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40 * 12 / NULLIF(SUM(TOTAL_SIZE_GB / 1024) * 40 * 12, 0) * 100, 2) AS "i. Yearly Savings (%)"
FROM combined
GROUP BY DB
ORDER BY DB;


-- AGGREGATION 3: Grand Total (All Databases)
WITH storage AS (
    SELECT TABLE_CATALOG AS DB, TABLE_SCHEMA AS SCH, TABLE_NAME AS TBL,
           ACTIVE_BYTES
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
    WHERE TABLE_CATALOG IN ('PROD_DATA','LDW','DELETED_TABLE')
      AND DELETED = FALSE AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA')
),
usage_lookback AS (
    SELECT DATABASE_NAME AS DB, SCHEMA_NAME AS SCH,
           REGEXP_SUBSTR(UPPER(QUERY_TEXT),'EBIKE_SIM_\\d+') AS TBL,
           MAX(CAST(REGEXP_SUBSTR(QUERY_TEXT,'DATEADD\\(day, -(\\d+)',1,1,'e') AS INT)) AS MAX_LOOKBACK_DAYS
    FROM SSNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE START_TIME >= DATEADD('month',-6,CURRENT_TIMESTAMP())
      AND DATABASE_NAME IN ('PROD_DATA','LDW','DELETED_TABLE')
      AND EXECUTION_STATUS = 'SUCCESS'
      AND UPPER(QUERY_TEXT) LIKE '%EBIKE_SIM_%'
      AND QUERY_TEXT LIKE '%DATEADD%'
    GROUP BY DB, SCH, TBL
),
combined AS (
    SELECT s.DB, s.SCH, s.TBL,
           ROUND(s.ACTIVE_BYTES / POWER(1024,3), 4) AS TOTAL_SIZE_GB,
           4383 AS TOTAL_DATA_DAYS,
           CASE WHEN u.MAX_LOOKBACK_DAYS IS NULL THEN 4383
                ELSE 4383 - u.MAX_LOOKBACK_DAYS END AS ARCHIVABLE_DAYS
    FROM storage s
    LEFT JOIN usage_lookback u ON s.DB = u.DB AND s.SCH = u.SCH AND s.TBL = u.TBL
)
SELECT 
    'ALL DATABASES' AS SCOPE,
    ROUND(SUM(TOTAL_SIZE_GB), 2) AS "a. Total Size (GB)",
    ROUND(SUM(TOTAL_SIZE_GB / 1024) * 40, 2) AS "b. Monthly Cost ($)",
    ROUND(SUM(TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)), 2) AS "d. Archivable Size (GB)",
    ROUND(SUM(TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / NULLIF(SUM(TOTAL_SIZE_GB), 0) * 100, 2) AS "e. Archivable %",
    ROUND(SUM((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40, 2) AS "f. Monthly Savings ($)",
    ROUND(SUM((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40 / NULLIF(SUM(TOTAL_SIZE_GB / 1024) * 40, 0) * 100, 2) AS "g. Monthly Savings (%)",
    ROUND(SUM((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40 * 12, 2) AS "h. Yearly Savings ($)",
    ROUND(SUM((TOTAL_SIZE_GB * (ARCHIVABLE_DAYS::FLOAT / TOTAL_DATA_DAYS)) / 1024) * 40 * 12 / NULLIF(SUM(TOTAL_SIZE_GB / 1024) * 40 * 12, 0) * 100, 2) AS "i. Yearly Savings (%)"
FROM combined;
